### PR TITLE
readd build dependencies

### PR DESCRIPTION
**Pull request by m4rc1e**
This PR should fix the CI so we get font builds. In an earlier PR, you deleted the scripts dir and makefile which I have readded. I've also bumped the dependencies so the fonts should now build.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Keep this open. I need to change some stuff.

**Comment by m4rc1e** [comment]
Alright, the ci is fixed. @SophiaDesign do you need to make any more changes or can we cut a release?

**Comment by SophiaDesign** [comment]
Thanks @m4rc1e, it looks like all is good except the static exports using gftools is not rendering the gradients properly. Could you let Marc know if we need the statics fixed @vv-monsalve @davelab6 ?

**Comment by vv-monsalve** [comment]
@SophiaDesign Inspecting and comparing the fonts (before and after leaving only two masters), evidently the font gradients are working ok in the variable, but not for the statics. On the other hand, there is also a difference in width between the two fonts. Do you recall adjusting any of that on the formerly extra masters added? In that case, they seem necessary for the font to behave as expected.

Please also inspect the alignment of the punctuation marks. Period, comma, colon, and semicolon are expected to share the baseline, while question and exclamdown are expected to go at the level of the x-height.
Screen Shot 2022-08-24 at 12 43 28

**VFs** (current font above)

Screen Shot 2022-08-24 at 12 30 03

**Statics** (current fonts above)

Screen Shot 2022-08-24 at 12 27 43
Screen Shot 2022-08-24 at 12 26 28

**Comment by SophiaDesign** [comment]
Thanks @vv-monsalve will adjust the punctuation marks

Infos about the export:
- fonttools version 4.36.0
- gftools version 0.9.15
- fontmake version 3.4.0
- python version 3.10.6

**Comment by SophiaDesign** [comment]
12th August 2022 export variates differently from before:
Aug-12-2022 16-02-09

before: Master for each instance
after: 2 Masters, number of instances increased by 1

**Comment by SophiaDesign** [comment]
Gradients on static TTF - Black master exists, but gradients still not rendered correctly.

Comparison of Foldit Black static TTF versus VF:
Screenshot 2022-08-24 at 19 12 13

**Comment by vv-monsalve** [comment]
@SophiaDesign I've run a new test using only fontmake with both source files (8 and 2 masters). 

**Generating ttf from instances** 
Both produce bad gradients for static ttf when interpolating.
`fontmake -g <source-file> -i -o ttf` command

Screen Shot 2022-08-24 at 22 34 50



**Generating ttf from masters instead** 
The gradients for statics only work when generating only the `master_ttfs` from the 8 masters file (hence the "Black-origin" name).
`fontmake -g <source-file> -o ttf` command
Screen Shot 2022-08-24 at 22 38 56


The gradients work ok for the VF using any of the source files, but the width still differs.
Screen Shot 2022-08-24 at 22 43 27

**Comment by vv-monsalve** [comment]
> @SophiaDesign I've run a new test using only fontmake with both source files (8 and 2 masters).
> 
> **Generating ttf from instances** Both produce bad gradients for static ttf when interpolating. `fontmake -g <source-file> -i -o ttf` command
> 
> Screen Shot 2022-08-24 at 22 34 50
> 
> **Generating ttf from masters instead** The gradients for statics only work when generating only the `master_ttfs` from the 8 masters file (hence the "Black-origin" name). `fontmake -g <source-file> -o ttf` command Screen Shot 2022-08-24 at 22 38 56
> 
> **Variable fonts** The gradients work ok for the VF using any of the source files, but the width still differs. Screen Shot 2022-08-24 at 22 43 27

**Comment by vv-monsalve** [comment]
@m4rc1e if the VFs are working ok, should this be reported on Fontmake for the gradients interpolation on statics?

**Comment by SophiaDesign** [comment]
@m4rc1e The proofs are the incorrect ones I'm afraid :-(

**Comment by m4rc1e** [comment]
Ok I see it as well now. Were they working at some point?

**Comment by m4rc1e** [comment]
I reckon this issue is happening because we're removing the overlaps in the static fonts. Let me gen a set which have overlaps intact.

**Comment by SophiaDesign** [comment]
Yep, the ones in main-backup branch in the static_ttf folder are good working COLRv1 TTFs. 

I tried to export them again yesterday with the new version of fonttools and it didn't come out right.

**Comment by SophiaDesign** [comment]
Going back to this branch has overwritten the creation date of the files. Is there any way I can still check the original? 

Then I'd be able to tell exactly what versions of python/gftools/fontmake I used based on my diary logs. If that would be of any help?

**Comment by m4rc1e** [comment]
My thoughts are correct.

Screenshot 2022-08-25 at 11 33 51
top: Broken ttf (generated with remove overlaps), middle: VF (correct), bottom: ttf with overlaps (correct)

It actually looks like fontmake is behaving as it should. Due to the design of the font, if we remove the overlaps, of course the gradients will change. What we should do is generate the ttfs and keep the overlaps like we've done in the bottom example. I can open a pr for this.

**Comment by vv-monsalve** [comment]
> Yep, the ones in main-backup branch in the static_ttf folder are good working COLRv1 TTFs.

Not quite, actually. If you inspect that [folder](https://github.com/SophiaDesign/Foldit/tree/main-backup/fonts/static_ttf) you can see that the "origin" name append to some font names. That means they were generated from the masters instead of the instances on the source file.

**Comment by m4rc1e** [comment]
Alright, Cosimo says they're not supported yet, https://github.com/googlefonts/fontmake/issues/928#issuecomment-1227311804.

Let's just get the VF out to google/fonts and we can always release the statics once they're supported.

**Comment by SophiaDesign** [comment]
already done 👍

**Comment by m4rc1e** [comment]
Awesome! so I can pr what we currently have to google/fonts?

**Comment by vv-monsalve** [comment]
I've inspected the font now and `colon` is still not good.
Screen Shot 2022-08-26 at 8 18 57

Other than that there is no FB Fails and VF still working.

**Comment by m4rc1e** [comment]
@SophiaDesign has the comma and colon been fixed? if we have nothing more to add, I'll cut a new release with version number `1.001`.

**Comment by SophiaDesign** [comment]
@m4rc1e I updated with a commit 5 days ago, which is same day as v1.000 release, but looks like it wasn't included in there

**Comment by vv-monsalve** [comment]
@SophiaDesign I've done the last fix on comma (it's at baseline level now, aligned to period and other punctuation marks) and merged it.
@m4rc1e I've created (two) new releases. The latest v1.002 would be the valid one since it includes the fixes in the decomposed source file.

**Comment by m4rc1e** [comment]
Fantastic! thank you Viv!

**Comment by vv-monsalve** [comment]
@m4rc1e, @SophiaDesign is reviewing the comma adjustments. Sophia, could you please confirm it before we go ahead with the publishing process?

**Comment by SophiaDesign** [comment]
Copying here from chat with @vv-monsalve :

> I saw that you moved the comma to align to the baseline. 
> 
> I made the choice to raise it deliberately for the Thin, as I thought it looked visually better. I realise it would look like a mistake compared to placement of the period, but when set it text instead of a specimen, this would look more natural. 
> 
> What do you think? Would it be possible to move them back up again? Placement for the Black was meant to be on the  baseline. Would this cause any issues?

And I agree with some suggestions for adjustments:

> My impression is the “head” of the comma is a little bit smaller (less tall) than the period and that is affecting its displaying. At the same time perhaps the “tale” could be slightly short and thin to reinforce its legibility

The changes have been applied in a new commit/push:
- Comma moved up
- Head size larger
- Tail longer
- some punctuation spacing tweaks

Screenshot 2022-09-01 at 12 05 52
Screenshot 2022-09-01 at 12 05 30
Screenshot 2022-09-01 at 12 06 27

**Comment by vv-monsalve** [comment]
> * Tail longer

I meant the opposite actually for the Thin master.
I'll pull the latest files.

**Pull request merged**
